//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.detail = new HashSet<detail>();
            this.order = new HashSet<order>();
        }
    
        public int idCar { get; set; }
        public string vincod { get; set; }
        public string registrNumber { get; set; }
        public int ModelOfCar_idModelOfCar { get; set; }
        public int ColorOfCar_idColorOfCar { get; set; }
        public int Client_idClient { get; set; }

        public List<detail> ListDetail { get; set; }
    
        public virtual client client { get; set; }
        public virtual colorofcar colorofcar { get; set; }
        public virtual modelofcar modelofcar { get; set; }
        public virtual ICollection<detail> detail { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
