//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class colorofcar
    {
        public colorofcar()
        {
            this.car = new HashSet<car>();
        }
    
        public int idColorOfCar { get; set; }
        public string nameColorOfCar { get; set; }
    
        public virtual ICollection<car> car { get; set; }
    }
}
