//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo
    {
        public int idPhoto { get; set; }
        public byte[] image { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public int Order_idOrder { get; set; }
    
        public virtual order order { get; set; }
    }
}
