//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        public process()
        {
            this.process_has_detail = new HashSet<process_has_detail>();
        }
    
        public int idProcess { get; set; }
        public Nullable<System.DateTime> dateTimeStart { get; set; }
        public Nullable<System.DateTime> dateTimeFinish { get; set; }
        public Nullable<System.DateTime> dateTimeStartFact { get; set; }
        public Nullable<System.DateTime> dateTimeFinishFact { get; set; }
        public int Worker_idWorker { get; set; }
        public int Operation_idOperation { get; set; }
        public int Order_idOrder { get; set; }

        public List<process_has_detail> ListProcess_has_detail { get; set; }
        public string NameDetails 
        {
            get 
            {
                string str = "";
                foreach (process_has_detail p in ListProcess_has_detail)
                    if (p.FlagProcess_has_detail)
                        str += ", " + p.detail.standartdetail.nameStandartDetail;
                if (str.Length > 2)
                    str = str.Substring(2);
                return str;
            }
        }
    
        public virtual operation operation { get; set; }
        public virtual order order { get; set; }
        public virtual ICollection<process_has_detail> process_has_detail { get; set; }
        public virtual worker worker { get; set; }
    }
}
