//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class process_has_detail
    {
        public int idProcess_has_Detail { get; set; }
        public int Process_idProcess { get; set; }
        public int Detail_idDetail { get; set; }

        public bool FlagProcess_has_detail { get; set; }

        public virtual detail detail { get; set; }
        public virtual process process { get; set; }
    }
}
