//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public skill()
        {
            this.workerhasskill = new HashSet<workerhasskill>();
        }
    
        public int idSkill { get; set; }
        public string nameSkill { get; set; }
    
        public virtual ICollection<workerhasskill> workerhasskill { get; set; }
    }
}
