//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class standartdetail
    {
        public standartdetail()
        {
            this.detail = new HashSet<detail>();
        }
    
        public int idStandartDetail { get; set; }
        public string nameStandartDetail { get; set; }
    
        public virtual ICollection<detail> detail { get; set; }
    }
}
