//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerhasskill
    {
        public int idWorkerHasSkill { get; set; }
        public Nullable<int> level { get; set; }
        public int Worker_idWorker { get; set; }
        public int Operation_idOperation { get; set; }
    
        public virtual operation operation { get; set; }
        public virtual worker worker { get; set; }
    }
}
