//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_system_third.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class workshopEntities_second : DbContext
    {
        public workshopEntities_second()
            : base("name=workshopEntities_second")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<car> car { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<colorofcar> colorofcar { get; set; }
        public DbSet<detail> detail { get; set; }
        public DbSet<markofcar> markofcar { get; set; }
        public DbSet<modelofcar> modelofcar { get; set; }
        public DbSet<operation> operation { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<photo> photo { get; set; }
        public DbSet<process> process { get; set; }
        public DbSet<process_has_detail> process_has_detail { get; set; }
        public DbSet<standartdetail> standartdetail { get; set; }
        public DbSet<worker> worker { get; set; }
        public DbSet<workerhasskill> workerhasskill { get; set; }
    }
}
